/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// replace the user pool region, id, and app client id details
export default {
    "REGION": 'eu-west-2',
    "USER_POOL_APP_CLIENT_ID": '5i0lluddheulv1sdotupcioub5',
    "USER_POOL_ID":'eu-west-2_X8yHvYuHE',
}

