/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// replace the user pool region, id, and app client id details
export default {
    "REGION": 'eu-west-2_DAdUW87I3',
    "USER_POOL_APP_CLIENT_ID": '4pj6cob86k9ubvh1dt8s1i0fsi',
    "USER_POOL_ID":'eu-west-2_DAdUW87I3',
}

